//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationResources.UserInterface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationResources.UserInterface.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, couldn&apos;t add manufacturer definition..
        /// </summary>
        public static string AddManufacturerError {
            get {
                return ResourceManager.GetString("AddManufacturerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string BadEmailOrPassword {
            get {
                return ResourceManager.GetString("BadEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was unexpected error with your serie or your solve..
        /// </summary>
        public static string ErrorWithSeriesOrSolves {
            get {
                return ResourceManager.GetString("ErrorWithSeriesOrSolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify at least one character in filter input..
        /// </summary>
        public static string FilterEmpty {
            get {
                return ResourceManager.GetString("FilterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This search filter returns too many results. Please make filter more specific..
        /// </summary>
        public static string FilterToManyResults {
            get {
                return ResourceManager.GetString("FilterToManyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend of last 50 series of your last serie category..
        /// </summary>
        public static string LastSeriesTrend {
            get {
                return ResourceManager.GetString("LastSeriesTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, couldn&apos;t modify this manufacturer..
        /// </summary>
        public static string ModifyManufacturerError {
            get {
                return ResourceManager.GetString("ModifyManufacturerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided new passwords are not equal..
        /// </summary>
        public static string NewPasswordsNotEqual {
            get {
                return ResourceManager.GetString("NewPasswordsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display..
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to update solves data..
        /// </summary>
        public static string NoDataToupdateSolves {
            get {
                return ResourceManager.GetString("NoDataToupdateSolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password request found for you email address..
        /// </summary>
        public static string NoPasswordRequest {
            get {
                return ResourceManager.GetString("NoPasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This serie does not contain any solve times..
        /// </summary>
        public static string NoSolvesInSerie {
            get {
                return ResourceManager.GetString("NoSolvesInSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal.
        /// </summary>
        public static string NotEqualPasswords {
            get {
                return ResourceManager.GetString("NotEqualPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we were not able to send you an email..
        /// </summary>
        public static string ResetPasswordEmailNotSend {
            get {
                return ResourceManager.GetString("ResetPasswordEmailNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just sent password reset code to the email address {0}..
        /// </summary>
        public static string ResetPasswordEmailSend {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were not able to add your request. Please try again later..
        /// </summary>
        public static string ResetPasswordRequestNotAdded {
            get {
                return ResourceManager.GetString("ResetPasswordRequestNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles assignment update for user {0} failed..
        /// </summary>
        public static string RolesAssignmentFailed {
            get {
                return ResourceManager.GetString("RolesAssignmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles assignment for user {0} successfully updated..
        /// </summary>
        public static string RolesAssignmentsChanged {
            get {
                return ResourceManager.GetString("RolesAssignmentsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to delete all solves from serie - delete whole serie..
        /// </summary>
        public static string SolvesAllDelete {
            get {
                return ResourceManager.GetString("SolvesAllDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops... Something wen wrong. W couldn&apos;t handle your request..
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such user does not exist in database..
        /// </summary>
        public static string UserDoNotExist {
            get {
                return ResourceManager.GetString("UserDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access to proceed with this action..
        /// </summary>
        public static string UserNoAccess {
            get {
                return ResourceManager.GetString("UserNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you do not own requested serie..
        /// </summary>
        public static string UserNotOwnsSerie {
            get {
                return ResourceManager.GetString("UserNotOwnsSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User pinning failed..
        /// </summary>
        public static string UserPinError {
            get {
                return ResourceManager.GetString("UserPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully pinned..
        /// </summary>
        public static string UserPinned {
            get {
                return ResourceManager.GetString("UserPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully unpinned..
        /// </summary>
        public static string UserUnpinned {
            get {
                return ResourceManager.GetString("UserUnpinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification key does not match. Please try again..
        /// </summary>
        public static string VerificationKeyDoesNotMatch {
            get {
                return ResourceManager.GetString("VerificationKeyDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong current password..
        /// </summary>
        public static string WrongCurrentPassword {
            get {
                return ResourceManager.GetString("WrongCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid solve duration format..
        /// </summary>
        public static string WrongDurationFormat {
            get {
                return ResourceManager.GetString("WrongDurationFormat", resourceCulture);
            }
        }
    }
}
