//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationResources.TimerDB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationResources.TimerDB.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be grather or equalt to {1}, and less than or equal to {2}..
        /// </summary>
        public static string ArgumentRange {
            get {
                return ResourceManager.GetString("ArgumentRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add category {0}..
        /// </summary>
        public static string CategoryAddAddFail {
            get {
                return ResourceManager.GetString("CategoryAddAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add category options set for category {0}..
        /// </summary>
        public static string CategoryAddOptionsSetFail {
            get {
                return ResourceManager.GetString("CategoryAddOptionsSetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} already exists..
        /// </summary>
        public static string CategoryAlreadyExists {
            get {
                return ResourceManager.GetString("CategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected category already has assigned scramble definition..
        /// </summary>
        public static string CategoryAlreadyHasScramble {
            get {
                return ResourceManager.GetString("CategoryAlreadyHasScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} cannot be deleted because it is used in at least one cube definition..
        /// </summary>
        public static string CategoryCannotDelete {
            get {
                return ResourceManager.GetString("CategoryCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category deletion failed..
        /// </summary>
        public static string CategoryDeleteFail {
            get {
                return ResourceManager.GetString("CategoryDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category modificationFailed..
        /// </summary>
        public static string CategoryModificationFailed {
            get {
                return ResourceManager.GetString("CategoryModificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such category does not exist..
        /// </summary>
        public static string CategoryNotExist {
            get {
                return ResourceManager.GetString("CategoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add category option {0}..
        /// </summary>
        public static string CategoryOptionAddFailed {
            get {
                return ResourceManager.GetString("CategoryOptionAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category option {0} already exists..
        /// </summary>
        public static string CategoryOptionAlreadyExists {
            get {
                return ResourceManager.GetString("CategoryOptionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category option {0} cannot be deleted, because it is used by options set of at least one category..
        /// </summary>
        public static string CategoryOptionCannotDelete {
            get {
                return ResourceManager.GetString("CategoryOptionCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category option {0} deletion failed..
        /// </summary>
        public static string CategoryOptionDeleteFailed {
            get {
                return ResourceManager.GetString("CategoryOptionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category option {0} does not exist..
        /// </summary>
        public static string CategoryOptionNotExist {
            get {
                return ResourceManager.GetString("CategoryOptionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected category option is not suitable for selected category..
        /// </summary>
        public static string CategoryOptionNotInCategory {
            get {
                return ResourceManager.GetString("CategoryOptionNotInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category option modification failed..
        /// </summary>
        public static string CategoryOptionUpdateFailed {
            get {
                return ResourceManager.GetString("CategoryOptionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cube addedd successfully..
        /// </summary>
        public static string CubeAddedSuccessfully {
            get {
                return ResourceManager.GetString("CubeAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cube adding failed..
        /// </summary>
        public static string CubeAddFailed {
            get {
                return ResourceManager.GetString("CubeAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cube is already in your collection..
        /// </summary>
        public static string CubeAlreadyInCollection {
            get {
                return ResourceManager.GetString("CubeAlreadyInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected cube cannot be deleted, because it is used in at least one rating, cubes collections or series..
        /// </summary>
        public static string CubeCannotDelete {
            get {
                return ResourceManager.GetString("CubeCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add cube to your cubes colection..
        /// </summary>
        public static string CubeCollectionAddFailed {
            get {
                return ResourceManager.GetString("CubeCollectionAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete full collection of cubes of single user..
        /// </summary>
        public static string CubeCollectionDeleteAllFailed {
            get {
                return ResourceManager.GetString("CubeCollectionDeleteAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete cube from your cubes collection..
        /// </summary>
        public static string CubeCollectionDeleteFailed {
            get {
                return ResourceManager.GetString("CubeCollectionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update cubes collection: {0} error(s)..
        /// </summary>
        public static string CubeCollectionUpdateFailed {
            get {
                return ResourceManager.GetString("CubeCollectionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube deleted successfully..
        /// </summary>
        public static string CubeDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CubeDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube deletion failed..
        /// </summary>
        public static string CubeDeleteFailed {
            get {
                return ResourceManager.GetString("CubeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube with passed parameters already exists..
        /// </summary>
        public static string CubeExists {
            get {
                return ResourceManager.GetString("CubeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specfied cube does not exist..
        /// </summary>
        public static string CubeNotExists {
            get {
                return ResourceManager.GetString("CubeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such cube in your cubes collection..
        /// </summary>
        public static string CubeNotInCollection {
            get {
                return ResourceManager.GetString("CubeNotInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube not rated before. Please add new rating first..
        /// </summary>
        public static string CubeNotRated {
            get {
                return ResourceManager.GetString("CubeNotRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube rating deleted successfully..
        /// </summary>
        public static string CuberatingDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CuberatingDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube rating deletion failed..
        /// </summary>
        public static string CubeRatingDeletionFailed {
            get {
                return ResourceManager.GetString("CubeRatingDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube rating update failed..
        /// </summary>
        public static string CubeRatingUpdateFailed {
            get {
                return ResourceManager.GetString("CubeRatingUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube rating successfully updated..
        /// </summary>
        public static string CubeRatingUpdateSuccessfull {
            get {
                return ResourceManager.GetString("CubeRatingUpdateSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube definition update failed..
        /// </summary>
        public static string CubeUpdateFailed {
            get {
                return ResourceManager.GetString("CubeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube definition updated successfully..
        /// </summary>
        public static string CubeUpdateSuccessfull {
            get {
                return ResourceManager.GetString("CubeUpdateSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of all ratings of user {0} failed..
        /// </summary>
        public static string DeleteUserAllRatings {
            get {
                return ResourceManager.GetString("DeleteUserAllRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all series data of user {0} failed with {1} errors. Total series amount: {2}..
        /// </summary>
        public static string DeletingUserSerieFailed {
            get {
                return ResourceManager.GetString("DeletingUserSerieFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} added successfully..
        /// </summary>
        public static string ManufacturerAddedSuccessfully {
            get {
                return ResourceManager.GetString("ManufacturerAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} adding failed..
        /// </summary>
        public static string ManufacturerAddFailed {
            get {
                return ResourceManager.GetString("ManufacturerAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} successfully deleted..
        /// </summary>
        public static string ManufacturerDeletionFailed {
            get {
                return ResourceManager.GetString("ManufacturerDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} deleted successfully..
        /// </summary>
        public static string ManufacturerDeletionSuccessfull {
            get {
                return ResourceManager.GetString("ManufacturerDeletionSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} already exists..
        /// </summary>
        public static string ManufacturerExists {
            get {
                return ResourceManager.GetString("ManufacturerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} cannot be deleted because it is used in at least one cube definition..
        /// </summary>
        public static string ManufacturerInUse {
            get {
                return ResourceManager.GetString("ManufacturerInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} is not defined..
        /// </summary>
        public static string ManufacturerNotDefined {
            get {
                return ResourceManager.GetString("ManufacturerNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} has been updated successfully..
        /// </summary>
        public static string ManufacturerUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ManufacturerUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer {0} update failed..
        /// </summary>
        public static string ManufacturerUpdateFailed {
            get {
                return ResourceManager.GetString("ManufacturerUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves list cannot contain duplicated moves..
        /// </summary>
        public static string MovesCollectionContainsDuplicates {
            get {
                return ResourceManager.GetString("MovesCollectionContainsDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided input data is invalid..
        /// </summary>
        public static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new plastic color failed..
        /// </summary>
        public static string PlasticColorAddFail {
            get {
                return ResourceManager.GetString("PlasticColorAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New color {0} added successfully..
        /// </summary>
        public static string PlasticColorAddSuccessfull {
            get {
                return ResourceManager.GetString("PlasticColorAddSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting plastic color {0} failed..
        /// </summary>
        public static string PlasticColorDeleteFailed {
            get {
                return ResourceManager.GetString("PlasticColorDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic color {0} successfully deleted..
        /// </summary>
        public static string PlasticColorDeletionSuccessfull {
            get {
                return ResourceManager.GetString("PlasticColorDeletionSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic color with name {0} already exists..
        /// </summary>
        public static string PlasticColorExists {
            get {
                return ResourceManager.GetString("PlasticColorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic color {0} cannot be deleted, because it is used in at least one cube defiinition..
        /// </summary>
        public static string PlasticColorInUse {
            get {
                return ResourceManager.GetString("PlasticColorInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic color {0} is not defined..
        /// </summary>
        public static string PlasticColorNotDefined {
            get {
                return ResourceManager.GetString("PlasticColorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube rating added successfully..
        /// </summary>
        public static string RatingAddedSuccessfully {
            get {
                return ResourceManager.GetString("RatingAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding cube rating failed..
        /// </summary>
        public static string RatingAddFailed {
            get {
                return ResourceManager.GetString("RatingAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already added rating for this cube..
        /// </summary>
        public static string RatingAlreadyMade {
            get {
                return ResourceManager.GetString("RatingAlreadyMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete default scramble..
        /// </summary>
        public static string ScrambleCanotDeleteDefault {
            get {
                return ResourceManager.GetString("ScrambleCanotDeleteDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set this scramble as default..
        /// </summary>
        public static string ScrambleDefaultSetFail {
            get {
                return ResourceManager.GetString("ScrambleDefaultSetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset default scramble..
        /// </summary>
        public static string ScrambleDefaultsResetFailed {
            get {
                return ResourceManager.GetString("ScrambleDefaultsResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create scramble definition..
        /// </summary>
        public static string ScrambleDefinitionAddFailed {
            get {
                return ResourceManager.GetString("ScrambleDefinitionAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete scramble definition..
        /// </summary>
        public static string ScrambleDefinitionDeletionFailed {
            get {
                return ResourceManager.GetString("ScrambleDefinitionDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble definition that you are traing to modifiy moves of does not exist..
        /// </summary>
        public static string ScrambleDoesNotExist {
            get {
                return ResourceManager.GetString("ScrambleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add new all new moves to scramble definition..
        /// </summary>
        public static string ScrambleMovesAddError {
            get {
                return ResourceManager.GetString("ScrambleMovesAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating scramble moves amount failed..
        /// </summary>
        public static string ScrambleMovesAmountUpdateError {
            get {
                return ResourceManager.GetString("ScrambleMovesAmountUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete previous scramble moves..
        /// </summary>
        public static string ScrambleMovesDeleteError {
            get {
                return ResourceManager.GetString("ScrambleMovesDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble with name {0} already exists for selected category..
        /// </summary>
        public static string ScrambleNameExists {
            get {
                return ResourceManager.GetString("ScrambleNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of scramble moves cannot be empty..
        /// </summary>
        public static string ScrambleNoMove {
            get {
                return ResourceManager.GetString("ScrambleNoMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new solve to already finished serie..
        /// </summary>
        public static string SerieAlreadyFinished {
            get {
                return ResourceManager.GetString("SerieAlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when tried to create serie..
        /// </summary>
        public static string SerieCreatingError {
            get {
                return ResourceManager.GetString("SerieCreatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete selected serie..
        /// </summary>
        public static string SerieDeletionFailed {
            get {
                return ResourceManager.GetString("SerieDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such serie does not exist..
        /// </summary>
        public static string SerieDoesNotExist {
            get {
                return ResourceManager.GetString("SerieDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update series finished condition..
        /// </summary>
        public static string SerieFinishUpdateFailed {
            get {
                return ResourceManager.GetString("SerieFinishUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This series belongs to different user..
        /// </summary>
        public static string SeriesBelongsToDiffuser {
            get {
                return ResourceManager.GetString("SeriesBelongsToDiffuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update series data after adding new solve..
        /// </summary>
        public static string SeriesUpdateFailed {
            get {
                return ResourceManager.GetString("SeriesUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new solve to series failed..
        /// </summary>
        public static string SolveAddFailed {
            get {
                return ResourceManager.GetString("SolveAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time {0} is shorter than acceptable time for this category, wchich is  {1}..
        /// </summary>
        public static string SolveBelowAcceptableTime {
            get {
                return ResourceManager.GetString("SolveBelowAcceptableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete solve from series..
        /// </summary>
        public static string SolvedeleteFailed {
            get {
                return ResourceManager.GetString("SolvedeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such solve does not exist..
        /// </summary>
        public static string SolveDoesNotExist {
            get {
                return ResourceManager.GetString("SolveDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update solve definition..
        /// </summary>
        public static string SolveUpdateFailed {
            get {
                return ResourceManager.GetString("SolveUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update selected scramble definition..
        /// </summary>
        public static string UpdateScrambleDefinitionFailed {
            get {
                return ResourceManager.GetString("UpdateScrambleDefinitionFailed", resourceCulture);
            }
        }
    }
}
