//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationResources.RequestsDB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationResources.RequestsDB.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user requests failed. Amount of requests: {0}, total amount of replies: {1}, amount of modified records: {2}..
        /// </summary>
        public static string DeletingUserRequestsFailed {
            get {
                return ResourceManager.GetString("DeletingUserRequestsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided message is too long. Max amount of characters is {0}..
        /// </summary>
        public static string MessageTooLong {
            get {
                return ResourceManager.GetString("MessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating specified request failed..
        /// </summary>
        public static string RequestAddFailed {
            get {
                return ResourceManager.GetString("RequestAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update request..
        /// </summary>
        public static string RequestAmountUpdateFailed {
            get {
                return ResourceManager.GetString("RequestAmountUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change state of request..
        /// </summary>
        public static string RequestCloseFailed {
            get {
                return ResourceManager.GetString("RequestCloseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request ID (request does not exist)..
        /// </summary>
        public static string RequestIdInvalid {
            get {
                return ResourceManager.GetString("RequestIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request was not create by you..
        /// </summary>
        public static string RequestNotBelongsToUser {
            get {
                return ResourceManager.GetString("RequestNotBelongsToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding response to request failed..
        /// </summary>
        public static string ResponseAddFailed {
            get {
                return ResourceManager.GetString("ResponseAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request that you are trying to add response to has already been closed..
        /// </summary>
        public static string ResponseRequestClosed {
            get {
                return ResourceManager.GetString("ResponseRequestClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided topic is too long. Max amount of characters is {0}..
        /// </summary>
        public static string TopicTooLong {
            get {
                return ResourceManager.GetString("TopicTooLong", resourceCulture);
            }
        }
    }
}
